### ISSUE TITLE
Getting a process error on Mailer.Deliver

### ISSUE THREAD

**Issue by jacklalley** [thoughtbot/bamboo#226]
Using `{:bamboo, "~> 0.7"}`

When I call`Mailer.deliver_later` or `Mailer.deliver_now` I get a process issue. At first I thought it was to do with my openssl version but I upgraded that to the latest version. Here is my bamboo setup. 

Config.exs (only included relevant part)

```
config :testing_fun, TestingFun.Mailer,
  adapter: Bamboo.SendgridAdapter,
  api_key: "API_KEY_HERE"
```

Mix.exs (tried to only include relevant code)

```
  def application do
    [mod: {TestingFun, []},
     applications: [:phoenix, :phoenix_pubsub, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :postgrex, :bamboo]]
  end

  defp deps do
    [{:phoenix, "~> 1.2.1"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.0"},
     {:bamboo, "~> 0.7"}]
  end
```

My email.ex and mailer.ex (both located in lib)

email.ex

```
defmodule TestingFun.Email do
  import Bamboo.Email

  def new_signup_email do
    new_email
     |> to("jack@lalley.com")
     |> from("notifications@test.co.uk")
     |> subject("New user signed up!")
     |> html_body("<strong>There's been a new user</strong>")
     |> text_body("There's been a new user")
  end
end
```

mailer.ex

```
defmodule TestingFun.Mailer do
  use Bamboo.Mailer, otp_app: :testing_fun
end
```

The error is the following: 

```
[error] ** State machine #PID<0.603.0> terminating
** Last event = {:internal, {:server_hello_done}}
** When server state  = [data: [{'State',
   {:certify,
    {:state, :client, {#Reference<0.0.1.1865>, #PID<0.597.0>}, :gen_tcp,
     :tls_connection, :tcp, :tcp_closed, :tcp_error, 'api.sendgrid.com', 443,
     #Port<0.20193>,
     {:ssl_options, :tls, [{3, 3}, {3, 2}, {3, 1}, {3, 0}], :verify_peer,
      {&:ssl_verify_hostname.verify_fun/3,
       [check_hostname: 'api.sendgrid.com']},
      #Function<0.129805300/1 in :hackney_connect.ssl_opts/2>, false, false,
      :undefined, 99, "", '***', "", '***', '***', '***', "", '***', :undefined,
      :undefined, '***', '***',
      [<<192, 44>>, <<192, 48>>, <<192, 36>>, <<192, 40>>, <<192, 8>>,
       <<192, 46>>, <<192, 50>>, <<192, 38>>, <<192, 42>>, <<0, 163>>,
       <<0, 106>>, <<0, ...>>, <<...>>, ...],
      #Function<1.9395691/4 in :ssl.handle_options/2>, true, 268435456, true,
      :undefined, :infinity, false, :undefined, :undefined, :undefined,
      :undefined, true, :undefined, ...},
     {:socket_options, :binary, :raw, 0, 0, false}, '***', '***', '***', 36884,
     '***', 57367, :ssl_session_cache, {:ssl_crl_cache, {{49171, 53266}, []}},
     {3, 3}, false, :ecdhe_rsa, {:sha, :rsa}, :undefined,
     {{1, 2, 840, 113549, 1, 1, 1},
      {:RSAPublicKey,
       27962469089060804281109342164745630861892952143742582405783174592503391660559146958964188663537302093087126879161749508355879108917217800277722148838320849507906712225968754208669864204316171862839536820873139584165582768116806230743537588163495793723313067624226876491347020996206446844794802318323404572555869888763295462079503084681560061175310697046220464841616490806923573165142315261764569548912052813658792251619823737112706436647200957234563544595319862832071156634024264576037645365023512448882482384054592619797353378615053167158518047144559272914094169757645509317918267434033214000507147215848217713505527,
       65537}, :NULL}, '***', '***', '***', :undefined, '***', '***', '***',
     40981, #Reference<0.0.1.1868>, :undefined, '***', {false, :first},
     {#PID<0.597.0>, #Reference<0.0.1.1866>}, #Reference<0.0.1.1870>, false,
     :undefined, false, false, :undefined, :undefined, :undefined, ...}}}]]
** Reason for termination = :error::notsup
** Callback mode = :state_functions
** Stacktrace =
**  [{:crypto, :aes_gcm_encrypt,
  [<<26, 57, 166, 248, 246, 207, 34, 196, 235, 97, 40, 139, 223, 152, 124,
     235>>, <<158, 247, 69, 205, 64, 238, 166, 220, 207, 164, 96, 54>>,
   <<0, 0, 0, 0, 0, 0, 0, 0, 22, 3, 3, 0, 16>>,
   [20, <<0, 0, 12>>, <<210, 248, 16, 180, 167, 97, 89, 254, 23, 87, 98, 234>>],
   16], []},
 {:ssl_cipher, :aead_cipher, 6, [file: 'ssl_cipher.erl', line: 167]},
 {:ssl_record, :cipher_aead, 4, [file: 'ssl_record.erl', line: 423]},
 {:tls_record, :encode_plain_text, 4, [file: 'tls_record.erl', line: 144]},
 {:tls_connection, :encode_handshake, 4,
  [file: 'tls_connection.erl', line: 471]},
 {:tls_connection, :queue_handshake, 2,
  [file: 'tls_connection.erl', line: 114]},
 {:tls_connection, :send_handshake, 2, [file: 'tls_connection.erl', line: 107]},
 {:ssl_connection, :client_certify_and_key_exchange, 2,
  [file: 'ssl_connection.erl', line: 1198]},
 {:gen_statem, :loop_event, 9, [file: 'gen_statem.erl', line: 878]},
 {:tls_connection, :init, 1, [file: 'tls_connection.erl', line: 172]},
 {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]

[error] Task #PID<0.597.0> started from #PID<0.589.0> terminating
** (stop) exited in: :gen_statem.call(#PID<0.603.0>, {:start, 8000}, :infinity)
    ** (EXIT) :notsup
    (stdlib) gen.erl:177: :gen.do_call/4
    (stdlib) gen_statem.erl:384: :gen_statem.call/3
    (ssl) ssl_connection.erl:1761: :ssl_connection.call/2
    (ssl) ssl_connection.erl:107: :ssl_connection.handshake/2
    (ssl) tls_connection.erl:85: :tls_connection.start_fsm/8
    (ssl) ssl_connection.erl:77: :ssl_connection.connect/8
    (hackney) src/hackney_connect.erl:246: :hackney_connect.do_connect/5
    (hackney) src/hackney_connect.erl:37: :hackney_connect.connect/5
    (hackney) src/hackney.erl:328: :hackney.request/5
    (httpoison) lib/httpoison/base.ex:402: HTTPoison.Base.request/9
    (httpoison) lib/httpoison.ex:66: HTTPoison.request!/5
    (bamboo) lib/bamboo/adapters/sendgrid_adapter.ex:61: Bamboo.SendgridAdapter.deliver/2
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.115485522/0 in Bamboo.TaskSupervisorStrategy.deliver_later/3>
    Args: []
```

**Comment by andre1sk** [comment]
Had similar error went away after upgrading to 19.1

**Comment by strangeworks** [comment]
@andre1sk @jacklalley could you provide your OS information, because notsup error might be caused because of incompatible OS arch.

**Comment by andre1sk** [comment]
OS X 10.11.6
had issues with Erlang Solutions package esl-erlang_18.3-1-osx-10.10_amd64.dmg
switched to  19.1 available from brew and problem went away

**Comment by paulcsmith** [comment]
@andre1sk Glad that fixed the issue! Thanks for posting this. I hope this also helps others in the future. Going to go ahead and close this now. Thanks!
