### ISSUE TITLE
Bamboo.MailgunAdapter.put_reply_to/2 blows up because its setting a string and not an atom

### ISSUE THREAD

**Issue by joshchernoff** [thoughtbot/bamboo#420]
Setting `"h:Reply-To",`  via 

```
  defp put_reply_to(body, %Email{headers: %{"reply-to" => address}}),
    do: Map.put(body, "h:Reply-To", address)
```
https://github.com/thoughtbot/bamboo/blob/6f10c5887a58ec7c3ace8b1fa8fa6fb3d9bf5c1a/lib/bamboo/adapters/mailgun_adapter.ex#L105

this will blow up blowing up because `"h:Reply-To"` gets passed set as a string in body, the when Enum.filter runs key (ie `"h:Reply-To"`) is what  is passed to Atom.to_string(key) as seen here
```
def filter_non_empty_mailgun_fields(body) do
    Enum.filter(body, fn {key, value} ->
      # Key is a well known mailgun field (including header and custom var field) and its value is not empty
      (key in @mailgun_message_fields || key in @internal_fields ||
         String.starts_with?(Atom.to_string(key), ["h:", "v:"])) && !(value in [nil, "", []])
    end)
    |> Enum.into(%{})
  end
```
https://github.com/thoughtbot/bamboo/blob/b0c66e5880ec970f5d46757a64bbebb14962659f/lib/bamboo/adapters/mailgun_adapter.ex#L171

You will end up with a:
```
** (ArgumentError) argument error
    :erlang.atom_to_binary("h:Reply-To", :utf8)
    (elixir) lib/enum.ex:900: anonymous fn/3 in Enum.filter/2
    (stdlib) lists.erl:1263: :lists.foldl/3
    (elixir) lib/enum.ex:1941: Enum.filter/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (iex) lib/iex/evaluator.ex:249: IEx.Evaluator.handle_eval/5
    (iex) lib/iex/evaluator.ex:229: IEx.Evaluator.do_eval/3
    (iex) lib/iex/evaluator.ex:207: IEx.Evaluator.eval/3
    (iex) lib/iex/evaluator.ex:94: IEx.Evaluator.loop/1
    (iex) lib/iex/evaluator.ex:24: IEx.Evaluator.init/4
    (iex) lib/iex/pry.ex:64: IEx.Pry.pry/2
    (bamboo) lib/bamboo/adapters/mailgun_adapter.ex:169: Bamboo.MailgunAdapter.filter_non_empty_mailgun_fields/1
    (bamboo) lib/bamboo/adapters/mailgun_adapter.ex:95: Bamboo.MailgunAdapter.to_mailgun_body/1
    (bamboo) lib/bamboo/adapters/mailgun_adapter.ex:51: Bamboo.MailgunAdapter.deliver/2
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
```

**Comment by joshchernoff** [comment]
Fixed/closing
