### ISSUE TITLE
Error: function Bamboo.SentEmailViewerPlug.handle_config/1 is undefined or private

### ISSUE THREAD

**Issue by wimwian** [thoughtbot/bamboo#562]
Hi, 

I am using Pow with email confirmation and receiving this error when I register as a new user. I am able to see the /sent_emails endpoint where it says there is no emails to display.

-Anand

Error:
```elixir
[error] #PID<0.819.0> running MyAppWeb.Endpoint (connection #PID<0.789.0>, stream id 10) terminated
Server: localhost:4000 (http)
Request: POST /session
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Bamboo.SentEmailViewerPlug.handle_config/1 is undefined or private
        (bamboo 1.6.0) Bamboo.SentEmailViewerPlug.handle_config(%{adapter: Bamboo.SentEmailViewerPlug})
        (bamboo 1.6.0) lib/bamboo/mailer.ex:293: Bamboo.Mailer.handle_adapter_config/1
        (my_app 0.5.0) lib/my_app/mailer.ex:2: MyApp.Mailer.deliver_later/2
        (pow 1.0.21) lib/extensions/email_confirmation/phoenix/controllers/controller_callbacks.ex:86: PowEmailConfirmation.Phoenix.ControllerCallbacks.halt_and_send_confirmation_email/2
        (elixir 1.11.1) lib/enum.ex:2181: Enum."-reduce/3-lists^foldl/2-0-"/3
        (pow 1.0.21) lib/pow/phoenix/controllers/controller.ex:100: Pow.Phoenix.Controller.action/3
        (pow 1.0.21) lib/pow/phoenix/controllers/session_controller.ex:1: Pow.Phoenix.SessionController.action/2
        (pow 1.0.21) lib/pow/phoenix/controllers/session_controller.ex:1: Pow.Phoenix.SessionController.phoenix_controller_pipeline/2
        (phoenix 1.5.6) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (my_app 0.5.0) lib/my_app_web/endpoint.ex:1: MyAppWeb.Endpoint.plug_builder_call/2
        (my_app 0.5.0) lib/plug/debugger.ex:132: MyAppWeb.Endpoint."call (overridable 3)"/2
        (my_app 0.5.0) lib/my_app_web/endpoint.ex:1: MyAppWeb.Endpoint.call/2
        (phoenix 1.5.6) lib/phoenix/endpoint/cowboy2_handler.ex:65: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.8.0) /home/apancha/my_app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.8.0) /home/apancha/my_app/deps/cowboy/src/cowboy_stream_h.erl:300: :cowboy_stream_h.execute/3
        (cowboy 2.8.0) /home/apancha/my_app/deps/cowboy/src/cowboy_stream_h.erl:291: :cowboy_stream_h.request_process/3
        (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
[info] GET /sent_emails
[debug] Processing with Bamboo.SentEmailViewerPlug
  Parameters: %{}
  Pipelines: []
[info] Sent 200 in 421µs
```

routes.ex configuration
```elixir
  scope "/" do
    pipe_through :browser

    pow_routes()
    pow_extension_routes()
    pow_assent_authorization_routes()
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
```

Mailer configuration
```elixir
defmodule MyApp.Mailer do
  use Bamboo.Mailer, otp_app: :my_app
end
```

Mail configuration
```elixir
defmodule MyAppWeb.Pow.Mailer do
  use Pow.Phoenix.Mailer

  import Bamboo.Email

  @impl true
  def cast(%{user: user, subject: subject, text: text, html: html}) do
    new_email(
      to: user.email,
      from: "abc@gmail.com",
      subject: subject,
      html_body: html,
      text_body: text
    )
  end

  @impl true
  def process(email), do: MyApp.Mailer.deliver_later(email)
end
```

```elixir
config :ng_time_sheet, NG.TimeSheet.Mailer,
  adapter: **Bamboo.SentEmailViewerPlug**
```

**Comment by wimwian** [comment]
Sorry for the false alarm. The dev.exs configuration mentioned the plug instead of LocalAdapter, which caused the issue.
